"""Add new model for Templates, Campaign CC Recipients and update Campaign recipient to align with these changes.

Revision ID: 3500d062e26c
Revises: 5b8e2abff74a
Create Date: 2026-06-03 03:10:18.472936

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3500d062e26c"
down_revision: str | Sequence[str] | None = "5b8e2abff74a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sender_addresses",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sender_addresses_user_id"),
        "sender_addresses",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "templates",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_templates_uploaded_by"), "templates", ["uploaded_by"], unique=False
    )
    op.create_table(
        "campaign_cc_recipients",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_cc_recipients_campaign_id"),
        "campaign_cc_recipients",
        ["campaign_id"],
        unique=False,
    )
    op.add_column("campaigns", sa.Column("template_id", sa.UUID(), nullable=True))
    op.add_column(
        "campaigns", sa.Column("from_address", sa.String(length=255), nullable=True)
    )
    op.create_foreign_key(
        "campaigns_template_id_fkey", "campaigns", "templates", ["template_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Named explicitly: autogenerate emitted None here, which is not a resolvable
    # constraint name. The literal matches PostgreSQL's default for the unnamed
    # FK this migration originally created, so already-migrated databases still
    # downgrade cleanly.
    op.drop_constraint("campaigns_template_id_fkey", "campaigns", type_="foreignkey")
    op.drop_column("campaigns", "from_address")
    op.drop_column("campaigns", "template_id")
    op.drop_index(
        op.f("ix_campaign_cc_recipients_campaign_id"),
        table_name="campaign_cc_recipients",
    )
    op.drop_table("campaign_cc_recipients")
    op.drop_index(op.f("ix_templates_uploaded_by"), table_name="templates")
    op.drop_table("templates")
    op.drop_index(op.f("ix_sender_addresses_user_id"), table_name="sender_addresses")
    op.drop_table("sender_addresses")
    # ### end Alembic commands ###
