web: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --proxy-headers --forwarded-allow-ips="*"
worker: celery -A server.workers.celery.celery_app worker --loglevel=info --concurrency=4
beat: celery -A server.workers.celery.celery_app beat --loglevel=info
