"""Set DNS_VALID as nullable and default STATUS is set as pending_validation in the campaign recipient model

Revision ID: 5b8e2abff74a
Revises: 9395bcd765d8
Create Date: 2026-06-01 03:46:03.542664

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5b8e2abff74a'
down_revision: str | Sequence[str] | None = '9395bcd765d8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_recipients', 'dns_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_recipients', 'dns_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
