"""add campaign recipient uniqueness

Revision ID: 9395bcd765d8
Revises: e945905bb8f5
Create Date: 2026-06-01 02:27:21.575987

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9395bcd765d8'
down_revision: str | Sequence[str] | None = 'e945905bb8f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_campaign_recipients_campaign_email', 'campaign_recipients', ['campaign_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_campaign_recipients_campaign_email', 'campaign_recipients', type_='unique')
    # ### end Alembic commands ###
